// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMTQDE_NfC7ehy1rtCW4nQczUb7ms8lvE',
    appId: '1:96813620456:web:c7bdebcc77c200b47d3d5d',
    messagingSenderId: '96813620456',
    projectId: 'easel-e5104',
    authDomain: 'easel-e5104.firebaseapp.com',
    storageBucket: 'easel-e5104.firebasestorage.app',
    measurementId: 'G-3ZZEP7WB5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQEzXJMhwZAiSs9Mwl8IuIN3lmtfaCzjY',
    appId: '1:96813620456:android:3f218fb0bcd80ff17d3d5d',
    messagingSenderId: '96813620456',
    projectId: 'easel-e5104',
    storageBucket: 'easel-e5104.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRpHiRF4jxj9jxaCvzn3gj6es6vO07Wfo',
    appId: '1:96813620456:ios:30c6ace25d092c387d3d5d',
    messagingSenderId: '96813620456',
    projectId: 'easel-e5104',
    storageBucket: 'easel-e5104.firebasestorage.app',
    iosBundleId: 'com.example.easel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRpHiRF4jxj9jxaCvzn3gj6es6vO07Wfo',
    appId: '1:96813620456:ios:30c6ace25d092c387d3d5d',
    messagingSenderId: '96813620456',
    projectId: 'easel-e5104',
    storageBucket: 'easel-e5104.firebasestorage.app',
    iosBundleId: 'com.example.easel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMTQDE_NfC7ehy1rtCW4nQczUb7ms8lvE',
    appId: '1:96813620456:web:a37e93999424b25b7d3d5d',
    messagingSenderId: '96813620456',
    projectId: 'easel-e5104',
    authDomain: 'easel-e5104.firebaseapp.com',
    storageBucket: 'easel-e5104.firebasestorage.app',
    measurementId: 'G-R1VGCLZC51',
  );
}
